# Generated by rust2rpm 11
%bcond_without check
%global debug_package %{nil}

%global crate warp

Name:           rust-%{crate}
Version:        0.1.20
Release:        2%{?dist}
Summary:        Serve the web at warp speeds

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/warp
Source:         %{crates_source}
# Initial patched metadata
# - Bump handlebars to 2.0.0
Patch0:         warp-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Serve the web at warp speeds.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+multipart-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multipart-devel %{_description}

This package contains library source intended for building other packages
which use "multipart" feature of "%{crate}" crate.

%files       -n %{name}+multipart-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages
which use "rustls" feature of "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages
which use "tls" feature of "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+tungstenite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tungstenite-devel %{_description}

This package contains library source intended for building other packages
which use "tungstenite" feature of "%{crate}" crate.

%files       -n %{name}+tungstenite-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+websocket-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+websocket-devel %{_description}

This package contains library source intended for building other packages
which use "websocket" feature of "%{crate}" crate.

%files       -n %{name}+websocket-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# Tests segfault on these arches
%ifarch %{arm} s390x
  %cargo_test || :
%else
  %cargo_test
%endif
%endif


%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.20-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Dec 13 17:33:01 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.1.20-1
- Update to 0.1.20

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.17-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jul 13 11:20:16 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.17-1
- Update to 0.1.17

* Tue Apr 02 2019 Josh Stone <jistone@redhat.com> - 0.1.15-1
- Update to 0.1.15

* Wed Mar 20 10:08:23 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.14-1
- Update to 0.1.14

* Thu Mar 14 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.13-1
- Initial package
